"""empty message

Revision ID: 8fc30dd6e553
Revises: 
Create Date: 2024-10-23 12:01:04.449980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fc30dd6e553'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preference_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('input_type', sa.String(), nullable=False),
    sa.Column('options', sa.String(), nullable=True),
    sa.Column('minval', sa.Integer(), nullable=True),
    sa.Column('maxval', sa.Integer(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('date_matching', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matcher_id', sa.Integer(), nullable=False),
    sa.Column('matchee_id', sa.Integer(), nullable=False),
    sa.Column('accepted', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['matchee_id'], ['users.id'], name=op.f('fk_likes_matchee_id_users')),
    sa.ForeignKeyConstraint(['matcher_id'], ['users.id'], name=op.f('fk_likes_matcher_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matcher_id', sa.Integer(), nullable=False),
    sa.Column('matchee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['matchee_id'], ['users.id'], name=op.f('fk_matches_matchee_id_users')),
    sa.ForeignKeyConstraint(['matcher_id'], ['users.id'], name=op.f('fk_matches_matcher_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('messagee', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_messages_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pref_category', sa.String(), nullable=False),
    sa.Column('pref_value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_preferences_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('attribute_category', sa.String(), nullable=False),
    sa.Column('attribute_value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_attributes_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_attributes')
    op.drop_table('preferences')
    op.drop_table('messages')
    op.drop_table('matches')
    op.drop_table('likes')
    op.drop_table('users')
    op.drop_table('preference_options')
    # ### end Alembic commands ###
