"""empty message

Revision ID: 9b75b69f5d17
Revises: b6f33d698995
Create Date: 2024-10-19 21:04:19.853066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b75b69f5d17'
down_revision = 'b6f33d698995'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preference_options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preference_options', schema=None) as batch_op:
        batch_op.drop_column('icon')

    # ### end Alembic commands ###
